title: Dhinesh
# subtitle: A Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  I am a computer science student.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact Me
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Dhinesh Subramanian
author_bio: Hey, my name is Dhinesh Subramanian. I am a Computer Science Student at SSNCE. 
author_email: "dhin.subramanian@gmail.com"
author_location: India
author_website_url: "https://dhinesh.ml"
typewrite-text: I am a Computer Science Student at SSNCE.

author_work_experiences:
            - company_name: LeanKloud
              company_logo: LeanKloud.jpeg
              company_url: http://leankloud.com/
              designation: Backend Intern
              description: Worked on building REST API using Flask and on Terraform (Infrastructure as Code)
              visibility: true
            - company_name: Exeter Premedia Services
              company_logo: exeter.png
              company_url: https://www.exeterpremedia.com/
              designation: Machine Learning Intern
              description: Worked on keyword extraction from research papers using NLP.
              visibility: true

author_education_details:
              - college_logo: ssn.jpg
                college_name: SSNCE
                college_url: https://www.ssn.edu.in/
                college_degree: Computer Science and Engineering
                description: Bachelor of Engineering
                visibility: true

author_project_details:
              - project_thumbnail: ethereum_dapp.png
                project_title: Overseas Money Transferr
                project_description: A money transfer app built on the Ethereum blockchain.
                project_url: https://github.com/dh1n3sh/EthereumPaymentApp
                visibility: true
              - project_thumbnail: covidence.jpeg
                project_title: Covidence
                project_description: Android application which serves features such as hospital/pharmacy/shelter/labs finder , geofencing of red-zones, UPI payment modes for donations and statistical data for different district. Built for Hackathon conducted by Anna University.
                project_url: https://github.com/dh1n3sh/CovidHack
                visibility: true

# social links
# twitter_username: johndoe
github_username:  dh1n3sh
# facebook_username: johndoe
linkedin_username: dh1n3sh
# behance_username: johndoe
instagram_username: dh1n3sh
# medium_username: johndoe

# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
